"""
skills/briefing/__init__.py  —  Daily Morning & Evening Briefings

Sends two narrative briefings per day via Telegram, generated by Claude:
  - Morning (8:00 AM London): calendar + tasks + motivational close
  - Evening (8:00 PM London): day recap + remaining tasks + warm close

Commands:
  /briefing           → morning briefing on demand
  /briefing evening   → evening briefing on demand

Scheduled automatically at startup via PTB's job_queue.
"""

from __future__ import annotations
import os
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

import anthropic
from supabase import create_client, Client
from telegram import Update
from telegram.ext import ContextTypes

from core.skill_base import BaseSkill, SkillResult, registry

_claude   = anthropic.Anthropic()
TIMEZONE  = "Europe/London"


class BriefingSkill(BaseSkill):
    name        = "briefing"
    description = "Daily morning and evening briefings"
    commands    = ["/briefing"]
    examples    = ["/briefing", "/briefing evening"]

    def __init__(self):
        self._db:   Client | None = None
        self._gcal = None   # Google Calendar service, borrowed from gcal skill

    async def on_load(self):
        url = os.getenv("SUPABASE_URL")
        key = os.getenv("SUPABASE_SERVICE_KEY")
        if url and key:
            self._db = create_client(url, key)

        # Borrow the already-authenticated Calendar service from the gcal skill
        try:
            from skills.gcal import _skill_instance as gcal_skill
            self._gcal = gcal_skill._service
        except Exception as e:
            print(f"[briefing] Could not borrow gcal service: {e}")

    # ── Commands ──────────────────────────────────────────────────────────────

    async def handle(self, update: Update, context: ContextTypes.DEFAULT_TYPE,
                     user_text: str, extracted: dict | None = None) -> SkillResult:
        uid = update.effective_user.id
        is_evening = any(w in user_text.lower() for w in ["evening", "night", "pm", "afternoon"])
        text = await self._build_evening(uid) if is_evening else await self._build_morning(uid)
        return SkillResult(text)

    # ── Scheduled senders ─────────────────────────────────────────────────────

    async def send_morning(self, bot) -> None:
        uid = self._owner_uid()
        if not uid:
            return
        text = await self._build_morning(uid)
        await bot.send_message(chat_id=uid, text=text, parse_mode="Markdown")

    async def send_evening(self, bot) -> None:
        uid = self._owner_uid()
        if not uid:
            return
        text = await self._build_evening(uid)
        await bot.send_message(chat_id=uid, text=text, parse_mode="Markdown")

    # ── Builders ──────────────────────────────────────────────────────────────

    async def _build_morning(self, uid: int) -> str:
        tz  = ZoneInfo(TIMEZONE)
        now = datetime.now(tz)

        events        = self._get_today_events(now, tz)
        todos         = self._get_todos(uid)
        work          = [t for t in todos if t.get("section") == "work"]
        personal      = [t for t in todos if t.get("section") != "work"]
        old_tasks     = self._get_old_tasks(todos, days=3)
        deadline_tasks= self._get_deadline_tasks(todos, within_days=3)

        ctx = self._morning_context(now, tz, events, work, personal, old_tasks, deadline_tasks)

        resp = _claude.messages.create(
            model      = "claude-sonnet-4-20250514",
            max_tokens = 500,
            system     = """You are Jorge's warm, thoughtful personal assistant sending his morning briefing on Telegram.

Write exactly 3 short paragraphs in a conversational, friendly tone — like a close friend who knows his life.
Use Telegram Markdown (*bold* only where it adds clarity, _italic_ for the closing line only).

Paragraph 1: what's on the calendar today — make it feel natural, not like a list.
Paragraph 2: what needs attention in tasks — mention specific names, note anything overdue or urgent.
Paragraph 3: one short motivational or encouraging line in italics. Keep it genuine, not cheesy.

No bullet points. No section headers. No emojis mid-sentence.""",
            messages   = [{"role": "user", "content": ctx}],
        )

        return f"☀️ *Good morning, Jorge!*\n\n{resp.content[0].text}"

    async def _build_evening(self, uid: int) -> str:
        tz  = ZoneInfo(TIMEZONE)
        now = datetime.now(tz)

        events   = self._get_today_events(now, tz)
        todos    = self._get_todos(uid)
        work     = [t for t in todos if t.get("section") == "work"]
        personal = [t for t in todos if t.get("section") != "work"]
        in_prog  = [t for t in todos if t.get("status") == "In Progress"]

        ctx = self._evening_context(now, tz, events, work, personal, in_prog)

        resp = _claude.messages.create(
            model      = "claude-sonnet-4-20250514",
            max_tokens = 400,
            system     = """You are Jorge's warm, thoughtful personal assistant sending his evening briefing on Telegram.

Write exactly 3 short paragraphs in a conversational, friendly tone — like a close friend who cares.
Use Telegram Markdown (*bold* only where it adds clarity, _italic_ for the closing line only).

Paragraph 1: briefly acknowledge the day — the calendar events that happened.
Paragraph 2: what's still in play — remaining tasks, keep it light and not stressful.
Paragraph 3: one warm, encouraging closing line in italics. Genuine, not corporate.

No bullet points. No section headers. No emojis mid-sentence.""",
            messages   = [{"role": "user", "content": ctx}],
        )

        return f"🌆 *Good evening, Jorge!*\n\n{resp.content[0].text}"

    # ── Data fetchers ─────────────────────────────────────────────────────────

    def _get_today_events(self, now: datetime, tz) -> list:
        if not self._gcal:
            return []
        try:
            day_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
            day_end   = day_start + timedelta(days=1)
            result    = self._gcal.events().list(
                calendarId  = "primary",
                timeMin     = day_start.isoformat(),
                timeMax     = day_end.isoformat(),
                singleEvents= True,
                orderBy     = "startTime",
                maxResults  = 15,
            ).execute()
            return result.get("items", [])
        except Exception as e:
            print(f"[briefing] Calendar fetch error: {e}")
            return []

    def _get_todos(self, uid: int) -> list:
        if not self._db:
            return []
        try:
            return self._db.table("todos").select("*").eq("user_id", uid).execute().data
        except Exception as e:
            print(f"[briefing] Todos fetch error: {e}")
            return []

    def _get_old_tasks(self, todos: list, days: int = 3) -> list:
        cutoff = datetime.now(ZoneInfo(TIMEZONE)) - timedelta(days=days)
        old = []
        for t in todos:
            if t.get("status") != "Pending":
                continue
            raw = t.get("created_at", "")
            try:
                dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
                if dt < cutoff:
                    old.append(t)
            except Exception:
                pass
        return old

    def _get_deadline_tasks(self, todos: list, within_days: int = 3) -> list:
        today = datetime.now(ZoneInfo(TIMEZONE)).date()
        result = []
        for t in todos:
            d = t.get("deadline", "—")
            if not d or d == "—":
                continue
            try:
                deadline_date = datetime.strptime(d, "%Y-%m-%d").date()
                if (deadline_date - today).days <= within_days:
                    result.append(t)
            except Exception:
                pass
        return result

    # ── Context builders ──────────────────────────────────────────────────────

    def _fmt_event(self, event: dict, tz) -> str:
        start_raw = event["start"].get("dateTime", event["start"].get("date"))
        if "T" in start_raw:
            dt = datetime.fromisoformat(start_raw).astimezone(tz)
            return f"{event.get('summary', 'Untitled')} at {dt.strftime('%H:%M')}"
        return f"{event.get('summary', 'Untitled')} (all day)"

    def _morning_context(self, now, tz, events, work, personal, old_tasks, deadline_tasks) -> str:
        parts = [f"Today is {now.strftime('%A %d %B %Y')}."]

        if events:
            parts.append("Calendar: " + "; ".join(self._fmt_event(e, tz) for e in events))
        else:
            parts.append("No calendar events today.")

        parts.append(
            f"Work tasks ({len(work)}): " + (", ".join(t["text"] for t in work) if work else "none")
        )
        parts.append(
            f"Personal tasks ({len(personal)}): " + (", ".join(t["text"] for t in personal) if personal else "none")
        )

        if old_tasks:
            parts.append(
                "Tasks pending for 3+ days (may need attention): "
                + ", ".join(t["text"] for t in old_tasks)
            )
        if deadline_tasks:
            parts.append(
                "Tasks with upcoming deadlines: "
                + ", ".join(f"{t['text']} (due {t['deadline']})" for t in deadline_tasks)
            )

        return "\n".join(parts)

    def _evening_context(self, now, tz, events, work, personal, in_prog) -> str:
        parts = [f"Today is {now.strftime('%A %d %B %Y')}, evening."]

        if events:
            parts.append("Today's calendar: " + "; ".join(self._fmt_event(e, tz) for e in events))
        else:
            parts.append("No calendar events today.")

        parts.append(
            f"Remaining work tasks ({len(work)}): " + (", ".join(t["text"] for t in work) if work else "none — all clear!")
        )
        parts.append(
            f"Remaining personal tasks ({len(personal)}): " + (", ".join(t["text"] for t in personal) if personal else "none — all clear!")
        )
        if in_prog:
            parts.append(
                "Still in progress: " + ", ".join(t["text"] for t in in_prog)
            )

        return "\n".join(parts)

    # ── Utility ───────────────────────────────────────────────────────────────

    def _owner_uid(self) -> int | None:
        raw = os.getenv("ALLOWED_USER_IDS", "")
        try:
            return int(raw.split(",")[0].strip())
        except (ValueError, IndexError):
            print("[briefing] Could not parse ALLOWED_USER_IDS")
            return None


_skill_instance = BriefingSkill()
registry.register(_skill_instance)
